#!/usr/bin/env node
import { readdir, mkdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import { CDN_BUNDLES, bundleDir, cdnShardOf } from './cdn-shard.mjs';

const args = process.argv.slice(2);
const flag = (name, fallback = null) => {
  const i = args.indexOf(`--${name}`);
  return i === -1 ? fallback : args[i + 1];
};
const has = (name) => args.includes(`--${name}`);

const SRC = path.resolve('public', 'cards');
const OUT = path.resolve('cdn');
const CONCURRENCY = Number(flag('concurrency', 8));
const ONLY = flag('only');
const FORCE = has('force');

const SIZES = [
  { width: 96, quality: 72 },
  { width: 320, quality: 72 },
  { width: 600, quality: 80 },
];

const FILE_LIMIT = 20_000;

const WARN_AT = 0.85;

const SPLIT = has('split');

const log = (...m) => console.log('[cdn]', ...m);

const SITE = (process.env.NEXT_PUBLIC_SITE_URL || 'https://carminelaluna.github.io').replace(/\/+$/, '');
const SITE_ORIGIN = new URL(SITE).origin;

const LOCK = has('lock');

const headers = () =>
  [
    '/*',
    '  Cache-Control: public, max-age=31536000, immutable',
    `  Access-Control-Allow-Origin: ${SITE_ORIGIN}`,
    '  X-Robots-Tag: noindex',
    '',
  ].join('\n');

async function writeGuard() {
  const source = `/**
 * Refuse requests that did not come from the site.
 *
 * Generated by scripts/build-cdn.mjs --lock. Read the note there before changing it:
 * this file is what makes every request to this bundle a Functions request rather
 * than a free static one.
 */
const SITE = ${JSON.stringify(SITE_ORIGIN)};

export async function onRequest(context) {
  const { request, next } = context;

  const referer = request.headers.get('referer') || '';
  /* Chromium sends this and it cannot be set by page JavaScript, unlike Referer. */
  const site = request.headers.get('sec-fetch-site') || '';

  const fromSite = referer.startsWith(SITE + '/') || referer === SITE;
  /* A reader with a strict referrer policy sends none; same-origin never needs one. */
  const allowed = fromSite || site === 'same-origin' || site === 'none';

  if (!allowed) {
    return new Response('Not available from this origin.', {
      status: 403,
      headers: { 'content-type': 'text/plain; charset=utf-8' },
    });
  }

  return next();
}
`;
  await mkdir(path.join(OUT, 'functions'), { recursive: true });
  await writeFile(path.join(OUT, 'functions', '_middleware.js'), source);
  log(`referrer check written — only ${SITE_ORIGIN} may embed these images`);
  log('NOTE: every request is now a Functions request, capped at 100,000/day on free');
}

async function unwriteGuard() {
  const dir = path.join(OUT, 'functions');
  if (!(await exists(dir))) return;
  await rm(dir, { recursive: true, force: true });
  log('removed the referrer check — requests are static and unmetered again');
}

const exists = (file) => stat(file).then(() => true).catch(() => false);

async function convert(name) {
  const id = path.basename(name, '.png');
  const source = path.join(SRC, name);
  let written = 0;
  let bytes = 0;

  const into = SPLIT ? path.join(OUT, bundleDir(cdnShardOf(id))) : OUT;

  for (const { width, quality } of SIZES) {
    const target = path.join(into, `${id}_${width}.webp`);
    if (!FORCE && (await exists(target))) {
      bytes += (await stat(target)).size;
      continue;
    }
    const buffer = await sharp(source)
      .resize({ width, withoutEnlargement: true })
      .webp({ quality, effort: 5 })
      .toBuffer();
    await writeFile(target, buffer);
    written++;
    bytes += buffer.length;
  }

  return { written, bytes };
}

async function main() {
  const started = Date.now();

  const all = (await readdir(SRC).catch(() => []))
    .filter((f) => f.endsWith('.png'))
    .filter((f) => !ONLY || f.toUpperCase().startsWith(ONLY.toUpperCase()));

  if (all.length === 0) {
    console.error('[cdn] no PNGs in public/cards — run `npm run ingest:images` first');
    process.exit(1);
  }

  const planned = all.length * SIZES.length;
  log(`${all.length} cards x ${SIZES.length} widths = ${planned.toLocaleString('en-US')} files`);

  const perBundle = SPLIT
    ? all.reduce((counts, name) => {
        counts[cdnShardOf(path.basename(name, '.png'))] += SIZES.length;
        return counts;
      }, new Array(CDN_BUNDLES).fill(0))
    : [planned];
  const fullest = Math.max(...perBundle);

  if (SPLIT) {
    log(
      `split across ${CDN_BUNDLES} bundles: ` +
        perBundle.map((n, i) => `${bundleDir(i)}=${n.toLocaleString('en-US')}`).join(', ')
    );
  }

  if (fullest > FILE_LIMIT * WARN_AT && fullest <= FILE_LIMIT) {
    log(
      `::warning::${fullest.toLocaleString('en-US')} files is ${Math.round((fullest / FILE_LIMIT) * 100)}% ` +
        `of the ${FILE_LIMIT.toLocaleString('en-US')} Cloudflare Pages allows per deployment` +
        (SPLIT ? '' : ' — `--split` writes two bundles, see scripts/cdn-shard.mjs')
    );
  }

  if (fullest > FILE_LIMIT && !ONLY) {
    console.error(
      `[cdn] ${fullest.toLocaleString('en-US')} files exceeds the Cloudflare Pages free limit ` +
        `of ${FILE_LIMIT.toLocaleString('en-US')}. ` +
        (SPLIT
          ? 'Both bundles are full; a paid plan allows 100,000.'
          : 'Run with `--split` to write two bundles — see scripts/cdn-shard.mjs.')
    );
    process.exit(1);
  }

  await mkdir(OUT, { recursive: true });
  if (SPLIT) {
    for (let i = 0; i < CDN_BUNDLES; i++) {
      await mkdir(path.join(OUT, bundleDir(i)), { recursive: true });
    }
  }

  let done = 0;
  let written = 0;
  let bytes = 0;
  let cursor = 0;

  await Promise.all(
    Array.from({ length: Math.min(CONCURRENCY, all.length) }, async () => {
      while (cursor < all.length) {
        const name = all[cursor++];
        try {
          const result = await convert(name);
          written += result.written;
          bytes += result.bytes;
        } catch (err) {
          console.error(`[cdn] ! ${name}: ${err.message}`);
        }
        if (++done % 500 === 0 || done === all.length) {
          const rate = done / ((Date.now() - started) / 1000);
          log(`${done}/${all.length}  ${rate.toFixed(0)}/s  ${(bytes / 1024 / 1024).toFixed(0)} MB`);
        }
      }
    })
  );

  if (SPLIT) {
    for (let i = 0; i < CDN_BUNDLES; i++) {
      await writeFile(path.join(OUT, bundleDir(i), '_headers'), headers());
    }
  } else {
    await writeFile(path.join(OUT, '_headers'), headers());
  }

  if (LOCK) await writeGuard();
  else await unwriteGuard();

  const totalFiles = all.length * SIZES.length;
  log(`done in ${((Date.now() - started) / 1000).toFixed(0)}s`);
  console.table({
    cards: all.length,
    files: totalFiles,
    'files left before the 20,000 limit': FILE_LIMIT - totalFiles,
    'newly converted': written,
    'total MB': Math.round(bytes / 1024 / 1024),
  });
  if (SPLIT) {
    log('upload both:');
    for (let i = 0; i < CDN_BUNDLES; i++) {
      log(`  npx wrangler pages deploy ./cdn/${bundleDir(i)} --project-name poneglyph-art-${bundleDir(i)}`);
    }
    log('then set NEXT_PUBLIC_CDN_URL and NEXT_PUBLIC_CDN_URL_B to the two hosts');
  } else {
    log('upload with:  npx wrangler pages deploy ./cdn --project-name poneglyph-art');
  }
}

main().catch((err) => {
  console.error('[cdn] FAILED —', err.message);
  process.exit(1);
});
